const people=[
 {name:'水城 遼',role:'北嶺日報・契約記者／主人公',want:'姉を捜し、事件を証明する。記者として実績も欲している。',conflict:'身内への執着と特報への欲望を「公益」で正当化する。',right:'設備記録と証言を分けて追う。',wrong:'未検証情報を公開し、新たな聴取者を生む。',open:'最終的に資料の記録者か、資料に記録される対象か。'},
 {name:'相原 紗季',role:'市危機管理課職員／最初の失踪者',want:'苦情と過去資料の不一致を確かめる。',conflict:'録音・文字起こし・行政資料を弟へ共有する。',right:'公式分類の外にある苦情を保存した。',wrong:'共有が救助か伝播か判断できないまま遼を巻き込む。',open:'遼を助けたのか、代わりの聞き手を求めたのか。'},
 {name:'柏木 修司',role:'消防団長／祭礼保存会役員',want:'旧鳴沢の被害を止める。',conflict:'八人目の資料を伏せ、久世に子局再接続を頼む。',right:'単純な放送停止では不十分だと知る。',wrong:'音の列で失踪者を旧避難路へ導く。',open:'保護・罪悪感・迷信のどれが沈黙の中心か。'},
 {name:'宗像 史郎',role:'寺の後継者／宗教学研究経験者',want:'信仰と共同体の罪悪感を切り分ける。',conflict:'過去帳の欠落を知るが、公開をためらう。',right:'寺の記録を正解として扱わない。',wrong:'沈黙が遼の疑念と対立を深める。',open:'過去帳の空欄が故意か、慣行か。'},
 {name:'瀬戸 真弓',role:'民俗学者／祭礼復元協力者',want:'断片的な慣行を記録し保存する。',conflict:'自分の採録が「伝統」を作った疑いを持つ。',right:'伝承の異同と採録過程を残す。',wrong:'標準語化と整理によって意味を固定した。',open:'復元が保存だったか、怪異への型の提供だったか。'},
 {name:'久世 岳',role:'防災無線・保守技術者',want:'設備の実態を合理的に切り分ける。',conflict:'廃子局を無許可再接続し、ログを改変する。',right:'中央から異常送信がないと示す。',wrong:'保身の改変で調査を遅らせる。',open:'廃子局の機械音をどこまで説明できるか。'},
 {name:'御厨 圭',role:'オカルト研究家・配信者',want:'現象を類型化し、自説を証明する。',conflict:'誤説で証人を傷つけたが、唯一の未加工録音を持つ。',right:'ネットに歪んで残った資料を保存した。',wrong:'「名を呼ばれた者が消える」と単純化した。',open:'創作体験談の未公表情報を誰から得たか。'},
 {name:'野辺 編集長',role:'北嶺日報・編集長',want:'公益性と検証可能性を守る。',conflict:'遼の記事を止めるため、隠蔽者に見える。',right:'危険な音声と文字列の公開を止める。',wrong:'記事の削除が重要証言も埋める。',open:'どこまで遼の未発表原稿を保存したか。'},
 {name:'相原 直子',role:'湖東台住民／紗季の義母',want:'紗季の捜索と情報公開。',conflict:'電話中の食器音と紗季の「お母さん」という発言を伏せる。',right:'行政へ継続的に照会する。',wrong:'家庭問題と誤解される恐れから初動証言を絞る。',open:'無人の台所で鳴った食器音の正体。'},
 {name:'佐伯 美緒',role:'湖東台住民／聴取03・第二失踪者',want:'亡母の声に聞こえた理由を知り、日常へ戻る。',conflict:'遼の公開文を読んだ後、同じ録音が母から自分の声へ変わる。',right:'返事をしていないことと聞こえ方の変化を正直に証言する。',wrong:'祭礼当日、一人で「何も聞こえない」ことを確かめに出る。',open:'声が暗示で変わったのか、彼女より先に移動したのか。'}
];
const evidence=[
 ['record','障害受付票','危機管理課','受付時刻・連絡先','職員による要約・分類'],['record','鳴沢避難事故報告','旧町役場','気象・道路・設備','人数・責任・添付欠落'],['record','保守点検票','久世岳','測定値・子局番号','無許可作業の未記載'],['audio','音声解析報告','外部検査機関','分析手順・環境音','元データの来歴'],['testimony','聞き取り記録','瀬戸真弓','語り手・採録日','標準語化・質問の影響'],['record','寺の過去帳','宗像家','家単位の法要記録','読み・追記・空欄'],['media','北嶺日報掲載記事','水城遼／編集部','日時・公式回答','見出し・削除証言'],['media','掲示板復元ログ','匿名投稿者群','流言の変化','時刻・転載・創作'],['audio','同一録音の文字起こし群','複数の聞き手','各人が聞いた内容','共通音声の客観的内容'],['record','共有フォルダ履歴','システム出力','ファイル操作の痕跡','時計・アカウント利用者'],['testimony','祭礼パンフレット','観光協会','現在の日程','由来・古さ'],['media','遼の未発表原稿','水城遼','一次証言の量','私情による因果の誘導']
];
const theories=[
 {id:'A',name:'土地の呼名現象',desc:'古い「呼び声」が時代ごとの伝達媒体を借りて現れる。名を呼ぶ／応じない慣行は、その現象への対処だった。',color:'var(--red)'},
 {id:'B',name:'共同体による人為的反復',desc:'事故の責任を抱える住民が鳴り物、設備、記録操作で現象を再現・維持した。罪悪感と暗示が内容差を生む。',color:'var(--amber)'},
 {id:'C',name:'記録と認識の伝播',desc:'音ではなく文字起こし、想起、記録によって「自分への放送」が成立する。資料が新しい聞き手を作る。',color:'var(--cyan)'}
];
const matrix=[['「呼名に応ぜず」','古い対処法','誤年代・後世の挿入','記録が認識を形成'],['子局の電力負荷','媒体を利用','無許可再接続','現象と同期'],['環境音一致・声不一致','聞き手別の声','加工・暗示','強く支持'],['八人目の名の揺れ','呼名対象の異常','隠蔽・転記','記録ごとに人物が変化'],['祭礼中の放送停止','防御儀礼','設備運用','注意・認識の遮断'],['停止後の失踪','祭礼は選別','人為策の失敗','音声は必須でない'],['廃子局の機械音','無電源設備の作動','作業・記録偽装','録音認識の改変']];
const chapters=[['序章','記録番号なし','3,000字','紗季から届く録音と短いメッセージ。内容を伏せ、末尾に椅子を引く音。'],['第1章','放送はありませんでした','12,000字','紗季失踪。送信ログなし。同じ録音から遼は自分の名を聞く。'],['第2章','聞こえたもの','13,000字','異なる証言。反響・誤聴・設備障害という合理説と、共有による連鎖疑惑。'],['第3章','呼名に応ぜず','14,000字','鳴沢避難事故、八人目、祭礼の再編集、廃子局。人為的隠蔽説が強まる。'],['第4章','同じ時刻の別の声','14,000字','創作怪談に未公表情報。環境音は一致するが、声だけが一致しない。'],['第5章','鳴らしているあいだ','14,000字','祭礼を復元し放送は止まる。しかし別の失踪が起きる。'],['第6章','未登録放送','15,000字','子局順から移動経路を復元。不正を暴き、点検坑で紗季を発見。'],['終章','聞取人不詳','5,000字','数年後の追補。第三の名と、録音受領以前の作成日時。']];
const sounds=[['放送前の無音','虫、車、空調など、本来あるはずの音が同時に消えたように感じる。'],['欠けた一音','チャイム、子守歌、祭囃子、録音に横断。明快な数対応は作らない。'],['遠近感のない声','音量ではなく、距離と方向を決められないことを描く。'],['遅れてくる返事','会話、山彦、録音の応答が一拍以上遅れる。'],['食器の触れ合う音','家庭の記憶と事故当夜を接続する生活音。'],['椅子を引く音','失踪者が立つ音か、誰かが席を用意する音か。']];
const checks=['中央操作卓に異常送信ログを書かない','久世が送るのは通常チャイムと鳴り物だけ','個別の呼名を人為放送だけで説明しない','録音・証言・設備・行動記録を混同しない','主要証拠を二仮説以上で説明できるようにする','古文書や専門家に正解を断言させない','柏木・久世・行政・寺を単純な悪役にしない','遼の報道にも被害を広げる側面を置く','第6章で人間側の事件を解く','終章で第6章の解決を無効にしない','終章の固有名詞を第4章までに提示する','最後に新しい能力・禁忌・黒幕を追加しない'];
const rejects=['怪異が防災無線を単純に乗っ取る一因一果','返事をすると必ず消える完全なゲームルール','町全体や秘密組織による万能な隠蔽','特殊周波数だけによる科学風の解答','専門家による真相の講義','全資料が嘘で推理不能な構成','最後の資料だけで超常を確定する結末'];

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id)); $$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id)); $('#sidebar').classList.remove('open'); window.scrollTo(0,0)}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('button');if(b)showView(b.dataset.view)}); $('#menu').onclick=()=>$('#sidebar').classList.toggle('open');
function renderPeople(){people.forEach((p,i)=>$('#people-list').insertAdjacentHTML('beforeend',`<button class="person-button searchable ${i?'':'active'}" data-i="${i}"><b>${String(i+1).padStart(2,'0')}</b><span><b>${p.name}</b><small>${p.role}</small></span></button>`)); selectPerson(0)}
function selectPerson(i){const p=people[i]; $$('.person-button').forEach((b,j)=>b.classList.toggle('active',i===j)); $('#dossier').innerHTML=`<span class="number">PERSONNEL / ${String(i+1).padStart(2,'0')}</span><h2>${p.name}</h2><p class="role">${p.role}</p><div class="dossier-grid"><div><b>欲求</b>${p.want}</div><div><b>葛藤・秘密</b>${p.conflict}</div><div><b>正しい判断</b>${p.right}</div><div><b>被害を広げる判断</b>${p.wrong}</div><div><b>意図的非確定</b>${p.open}</div></div>`}
$('#people-list').addEventListener('click',e=>{const b=e.target.closest('button');if(b)selectPerson(+b.dataset.i)});
function renderEvidence(filter='all'){$('#evidence-grid').innerHTML=evidence.filter(x=>filter==='all'||x[0]===filter).map(x=>`<article class="evidence-card searchable" role="button" tabindex="0" data-evidence-title="${x[1]}"><span class="type">${x[0].toUpperCase()} / ${x[2]}</span><span class="meetings-badge">3会議・6記録</span><h2>${x[1]}</h2><div class="axis"><b>信頼できる軸</b><p>${x[3]}</p></div><div class="axis doubt"><b>疑う軸</b><p>${x[4]}</p></div></article>`).join('')}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderMarkdown(md){let html=escapeHtml(md);html=html.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/^[-*] (.+)$/gm,'<li>$1</li>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/^([^<\n].+)$/gm,'<p>$1</p>');html=html.replace(/(?:<li>.*?<\/li>\n?)+/gs,m=>`<ul>${m}</ul>`);html=html.replace(/<p>(議長|調査報道|記者|民俗学|宗教学|オカルト|音響通信|音響・通信|構成・整合性監査|整合性監査)([：:])/g,'<p><span class="speaker">$1$2</span>');return html}
function recordForTitle(title){return (window.meetingData||[]).find(r=>r.profile.includes(title)||r.title.includes(title))}
function meetingLabel(n){return ['','成立背景・作成者・目的','具体内容・矛盾・伏線','作中配置・公平性監査'][n]}
function openEvidenceDetail(title){const record=recordForTitle(title);const box=$('#detail-content');if(!record){box.innerHTML=`<p class="detail-kicker">EVIDENCE MEETINGS</p><h2 class="detail-title">${escapeHtml(title)}</h2><div class="detail-empty">会議記録を読み込み中です。</div>`}else{box.innerHTML=`<p class="detail-kicker">EVIDENCE MEETINGS / ${escapeHtml(record.id)}</p><h2 class="detail-title">${escapeHtml(title)}</h2><p class="detail-sub">三段階の専門家会議で、資料の成立から作中配置まで設計。</p><div class="meeting-count"><span>会議 3回</span><span>文字起こし 3本</span><span>議事録 3本</span></div><div class="markdown profile-markdown">${renderMarkdown(record.profile)}</div>${record.meetings.map(m=>`<section class="meeting-block"><button class="meeting-head"><span>MEETING ${m.number}</span><b>${meetingLabel(m.number)}</b><i>＋</i></button><div class="meeting-body"><div class="meeting-switch"><button class="active" data-kind="transcript">文字起こし</button><button data-kind="minutes">議事録</button></div><div class="meeting-text markdown" data-transcript="${encodeURIComponent(m.transcript)}" data-minutes="${encodeURIComponent(m.minutes)}">${renderMarkdown(m.transcript)}</div></div></section>`).join('')}`};$('#evidence-detail').classList.add('open');$('#evidence-detail').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeEvidenceDetail(){$('#evidence-detail').classList.remove('open');$('#evidence-detail').setAttribute('aria-hidden','true');document.body.style.overflow=''}
$('#evidence-grid').addEventListener('click',e=>{const card=e.target.closest('.evidence-card');if(card)openEvidenceDetail(card.dataset.evidenceTitle)});
$('#evidence-grid').addEventListener('keydown',e=>{const card=e.target.closest('.evidence-card');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openEvidenceDetail(card.dataset.evidenceTitle)}});
$('#detail-close').onclick=closeEvidenceDetail;$('#detail-backdrop').onclick=closeEvidenceDetail;
$('#detail-content').addEventListener('click',e=>{const head=e.target.closest('.meeting-head');if(head){const block=head.parentElement;block.classList.toggle('open');head.querySelector('i').textContent=block.classList.contains('open')?'−':'＋';return}const sw=e.target.closest('.meeting-switch button');if(sw){const body=sw.closest('.meeting-body');body.querySelectorAll('.meeting-switch button').forEach(b=>b.classList.toggle('active',b===sw));const text=body.querySelector('.meeting-text');text.innerHTML=renderMarkdown(decodeURIComponent(text.dataset[sw.dataset.kind]))}});
$('#evidence-filters').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return; $$('#evidence-filters button').forEach(x=>x.classList.toggle('active',x===b));renderEvidence(b.dataset.filter)});
function renderTheories(){$('#theory-tabs').innerHTML=theories.map((t,i)=>`<button class="${i?'':'active'}" data-i="${i}">${t.id} / ${t.name}</button>`).join(''); selectTheory(0); $('#matrix').innerHTML=matrix.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}
function selectTheory(i){const t=theories[i];$$('#theory-tabs button').forEach((b,j)=>b.classList.toggle('active',i===j));$('#theory-detail').innerHTML=`<span class="tag theory">仮説 ${t.id}</span><h2 style="color:${t.color}">${t.name}</h2><p>${t.desc}</p><small>この仮説だけでは全証拠を説明できない。三仮説は複合している可能性がある。</small>`}
$('#theory-tabs').addEventListener('click',e=>{const b=e.target.closest('button');if(b)selectTheory(+b.dataset.i)});
function renderChapters(){$('#chapter-list').innerHTML=chapters.map((c,i)=>`<article class="chapter searchable"><button><span>${c[0]}</span><b>${c[1]}</b><small>${c[2]}</small></button><div class="chapter-detail"><p>${c[3]}</p></div></article>`).join('')}
$('#chapter-list').addEventListener('click',e=>{const b=e.target.closest('button');if(b)b.parentElement.classList.toggle('open')});
function renderSounds(){$('#sound-grid').innerHTML=sounds.map(s=>`<article class="sound-card searchable"><i></i><h2>${s[0]}</h2><p>${s[1]}</p></article>`).join('')}
function renderRules(){const saved=JSON.parse(localStorage.getItem('horror-checks')||'[]');$('#checklist').innerHTML=checks.map((x,i)=>`<label class="check ${saved.includes(i)?'done':''}"><input type="checkbox" data-i="${i}" ${saved.includes(i)?'checked':''}><span>${x}</span></label>`).join('');$('#reject-list').innerHTML=rejects.map(x=>`<li>${x}</li>`).join('')}
$('#checklist').addEventListener('change',()=>{const done=$$('#checklist input:checked').map(x=>+x.dataset.i);localStorage.setItem('horror-checks',JSON.stringify(done));$$('.check').forEach(x=>x.classList.toggle('done',x.querySelector('input').checked));toast('チェック状態を保存しました')});
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
$('.map').addEventListener('click',e=>{const b=e.target.closest('.place');if(!b)return;$$('.place').forEach(x=>x.classList.toggle('selected',x===b));const target=[...$('#place-details').children].find(x=>x.querySelector('h2').textContent===b.dataset.place);target?.scrollIntoView({behavior:'smooth',block:'center'})});
function search(q){q=q.trim().toLowerCase();let count=0;$$('.searchable').forEach(el=>{const hit=!q||el.textContent.toLowerCase().includes(q);el.classList.toggle('search-hidden',!hit);if(hit)count++});$('#empty').style.display=q&&count===0?'block':'none'}
$('#search').addEventListener('input',e=>search(e.target.value));document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape'){$('#search').value='';search('');$('#search').blur()}});
function inlineDocument(s){return escapeHtml(s).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`(.+?)`/g,'<code>$1</code>')}
function renderDocumentMarkdown(md){const lines=String(md||'').split('\n');let out='',i=0,inCode=false,code=[];while(i<lines.length){const line=lines[i];if(line.startsWith('```')){if(inCode){out+=`<pre><code>${escapeHtml(code.join('\n'))}</code></pre>`;code=[]}inCode=!inCode;i++;continue}if(inCode){code.push(line);i++;continue}if(/^\|.+\|$/.test(line)&&i+1<lines.length&&/^\|[\s:|-]+\|$/.test(lines[i+1])){const heads=line.split('|').slice(1,-1).map(x=>x.trim());i+=2;const rows=[];while(i<lines.length&&/^\|.+\|$/.test(lines[i])){rows.push(lines[i].split('|').slice(1,-1).map(x=>x.trim()));i++}out+=`<div class="matrix-wrap"><table><thead><tr>${heads.map(x=>`<th>${inlineDocument(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${inlineDocument(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;continue}if(/^# /.test(line))out+=`<h1>${inlineDocument(line.slice(2))}</h1>`;else if(/^## /.test(line))out+=`<h2>${inlineDocument(line.slice(3))}</h2>`;else if(/^### /.test(line))out+=`<h3>${inlineDocument(line.slice(4))}</h3>`;else if(/^> /.test(line)){const q=[];while(i<lines.length&&/^> ?/.test(lines[i])){q.push(lines[i].replace(/^> ?/,''));i++}out+=`<blockquote>${q.map(x=>`<p>${inlineDocument(x)}</p>`).join('')}</blockquote>`;continue}else if(/^[-*] /.test(line)){const items=[];while(i<lines.length&&/^[-*] /.test(lines[i])){items.push(lines[i].slice(2));i++}out+=`<ul>${items.map(x=>`<li>${inlineDocument(x)}</li>`).join('')}</ul>`;continue}else if(/^\d+\. /.test(line)){const items=[];while(i<lines.length&&/^\d+\. /.test(lines[i])){items.push(lines[i].replace(/^\d+\. /,''));i++}out+=`<ol>${items.map(x=>`<li>${inlineDocument(x)}</li>`).join('')}</ol>`;continue}else if(/^---+$/.test(line))out+='<hr>';else if(line.trim())out+=`<p>${inlineDocument(line)}</p>`;i++}return out}
function renderDocuments(){const records=(window.meetingData||[]).filter(r=>r.document);$('#document-list').innerHTML=records.map((r,i)=>{const title=(r.document.match(/^# (.+)$/m)||[])[1]||r.title;return `<article class="document-item searchable"><button><span>${String(i+1).padStart(2,'0')}</span><b>${escapeHtml(title)}</b><i>＋</i></button><div class="document-paper markdown">${renderDocumentMarkdown(r.document)}</div></article>`}).join('')}
$('#document-list').addEventListener('click',e=>{const b=e.target.closest('.document-item>button');if(!b)return;const item=b.parentElement;item.classList.toggle('open');b.querySelector('i').textContent=item.classList.contains('open')?'−':'＋'});
renderPeople();renderEvidence();renderTheories();renderChapters();renderSounds();renderRules();renderDocuments();
